// <auto-generated />
using MebOkullar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MebOkullar.Migrations
{
    [DbContext(typeof(MebDbContext))]
    [Migration("20250919133346_CreateOzelOkullarTable")]
    partial class CreateOzelOkullarTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MebOkullar.Models.Okul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HOST")
                        .HasColumnType("text");

                    b.Property<string>("OKUL_ADI")
                        .HasColumnType("text");

                    b.Property<string>("YOL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Okullar");
                });

            modelBuilder.Entity("MebOkullar.Models.OzelOkul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OzelOkullar");
                });
#pragma warning restore 612, 618
        }
    }
}
