// <auto-generated />
using MebOkullar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MebOkullar.Migrations
{
    [DbContext(typeof(MebDbContext))]
    [Migration("20250921090814_AddOzelYurtlarTable")]
    partial class AddOzelYurtlarTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MebOkullar.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("EgitimProgramları")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kurslar");
                });

            modelBuilder.Entity("MebOkullar.Models.OgrenciEtkinlikMerkezleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OgrenciEtkinlikMerkezleri");
                });

            modelBuilder.Entity("MebOkullar.Models.Okul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HOST")
                        .HasColumnType("text");

                    b.Property<string>("OKUL_ADI")
                        .HasColumnType("text");

                    b.Property<string>("YOL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Okullar");
                });

            modelBuilder.Entity("MebOkullar.Models.OzelOgretimKurslari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OzelOgretimKurslari");
                });

            modelBuilder.Entity("MebOkullar.Models.OzelOkul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OzelOkullar");
                });

            modelBuilder.Entity("MebOkullar.Models.OzelYurtlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OzelYurtlar");
                });

            modelBuilder.Entity("MebOkullar.Models.RehabilitasyonMerkezleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("EgitimProgramları")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RehabilitasyonMerkezleri");
                });

            modelBuilder.Entity("MebOkullar.Models.SosyalEtkinlikGelisimMerkezleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("EgitimProgramları")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SosyalEtkinlikGelisimMerkezleri");
                });

            modelBuilder.Entity("MebOkullar.Models.SosyalEtkinlikMerkezleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("EgitimProgramları")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SosyalEtkinlikMerkezleri");
                });

            modelBuilder.Entity("MebOkullar.Models.SurucuKurslari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("text");

                    b.Property<string>("KurumTuru")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SurucuKurslari");
                });
#pragma warning restore 612, 618
        }
    }
}
